"""empty message

Revision ID: b06d443cdd0c
Revises: b99c70076c42
Create Date: 2024-10-27 21:50:12.544971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b06d443cdd0c'
down_revision: Union[str, None] = 'b99c70076c42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('message_thread_id_fkey', 'message', type_='foreignkey')
    op.create_foreign_key(None, 'message', 'thread', ['thread_id'], ['id'], ondelete='set null')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.create_foreign_key('message_thread_id_fkey', 'message', 'thread', ['thread_id'], ['id'])
    # ### end Alembic commands ###
